apiVersion: v1
kind: Namespace
metadata:
  name: caddy-system
  labels:
    app.kubernetes.io/name: caddy
    app.kubernetes.io/part-of: martianbank
    environment: dlmdccco01-dev
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
---
apiVersion: v1
kind: Namespace
metadata:
  name: martianbank-app
  labels:
    app.kubernetes.io/name: martianbank-app
    app.kubernetes.io/part-of: martianbank
    environment: dlmdccco01-dev
    network-segment: app
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
---
apiVersion: v1
kind: Namespace
metadata:
  name: martianbank-data
  labels:
    app.kubernetes.io/name: martianbank-data
    app.kubernetes.io/part-of: martianbank
    environment: dlmdccco01-dev
    network-segment: data
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
---
apiVersion: v1
kind: Namespace
metadata:
  name: martianbank-observability
  labels:
    app.kubernetes.io/name: martianbank-observability
    app.kubernetes.io/part-of: martianbank
    environment: dlmdccco01-dev
    network-segment: observability
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
