apiVersion: v1
kind: ConfigMap
metadata:
  name: martianbank-config
  namespace: martianbank-app
  labels:
    app.kubernetes.io/name: martianbank
    app.kubernetes.io/part-of: martianbank
    environment: dlmdccco01-dev
data:
  SERVICE_PROTOCOL: "http"
  ACCOUNT_HOST: "accounts"
  TRANSACTION_HOST: "transactions"
  LOAN_HOST: "loan"
  CUSTOMER_AUTH_HOST: "customer-auth"
  ATM_LOCATOR_HOST: "atm-locator"
  NODE_ENV: "production"
  VITE_USERS_URL: "/api/users"
  VITE_ATM_URL: "/api/atm"
  VITE_ACCOUNTS_URL: "/api/account"
  VITE_TRANSFER_URL: "/api/transaction"
  VITE_LOAN_URL: "/api/loan"
